### ISSUE TITLE
Jvm bug?

### ISSUE THREAD

**Issue by CXwudi** [CXwudi/kotlin-jvm-idiomatic-exec#1]
we are unsure if this is a bug in JVM, because I wouldn't get this log from Java 11 when running test  
also, this seems to not consistently appear
```
Exception in thread "null-null-stdout" java.io.IOException: Stream closed
	at java.base/java.io.BufferedInputStream.getInIfOpen(BufferedInputStream.java:157)
	at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:282)
	at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:343)
	at java.base/sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:270)
	at java.base/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:313)
	at java.base/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:188)
	at java.base/java.io.InputStreamReader.read(InputStreamReader.java:177)
	at java.base/java.io.BufferedReader.fill(BufferedReader.java:162)
	at java.base/java.io.BufferedReader.readLine(BufferedReader.java:329)
	at java.base/java.io.BufferedReader.readLine(BufferedReader.java:396)
	at kotlin.io.LinesSequence$iterator$1.hasNext(ReadWrite.kt:80)
	at kotlin.io.TextStreamsKt.forEachLine(ReadWrite.kt:155)
```

**Comment by CXwudi** [comment]
we can't reproduce it on docker, consider running in wsl2 to give a try  
can also try using normal java instead of graalvm
